# Nombre del workflow
name: CI - API Plantas Dockerizada

on:
  push:
    branches: [main]  # push a main
  pull_request:
    branches: [main]  # PR hacia main

# Primer Job: Revisión de sintaxis PHP (Lint)
jobs:
  lint:
    name: Lint PHP
    runs-on: ubuntu-latest  # GitHub usa una máquina virtual Ubuntu

    steps:
      - name: Clonar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependencias con Composer
        run: composer install

      - name: Ejecutar análisis de sintaxis (Lint)
        run: |
          find . -type f -name "*.php" -exec php -l {} \;

# Construir imagen Docker y subirla a DockerHub
  docker:
    name: Build y Push Imagen Docker
    needs: lint  # Este job solo se ejecuta si el Lint pasó exitosamente
    runs-on: ubuntu-latest

    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api-plantas:latest .

      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api-plantas:latest
